parameters:
    default_database_driver:   pdo_mysql
    default_database_host:     115.28.105.41
    default_database_port:     3306
    default_database_name:     dongxihu_evaluation
    default_database_user:     user
    default_database_password: aliyun@zmy#5201314

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
