parameters:
    default_database_driver:   pdo_mysql
    default_database_host:     127.0.0.1
    default_database_port:     3306
    default_database_name:     dongxihu_evaluation
    default_database_user:     root
    default_database_password: zmy@5201314

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
