evaluation_admin:
    resource: "@EvaluationAdminBundle/Resources/config/routing.yml"
    prefix:   /

evaluation_web:
    resource: "@EvaluationWebBundle/Resources/config/routing.yml"
    prefix:   /

evaluation_common:
    resource: "@EvaluationCommonBundle/Resources/config/routing.yml"
    prefix:   /












