security:
     firewalls:
     	admin_secured_area:
     	    provider: evaluation_admin
            pattern: ^/
            anonymous: ~
            form_login: 
                login_path: evaluation_admin_login
                check_path: evaluation_admin_login_check
                always_use_default_target_path: true
                default_target_path: evaluation_admin_console
            logout:
                path: evaluation_admin_logout
                target: evaluation_admin_login
            
     access_control: 
                 - { path: ^/admin$, roles:  IS_AUTHENTICATED_ANONYMOUSLY }
                 - { path: ^/admin/, roles: ROLE_ADMIN }
                 
     providers:
          evaluation_admin:
               memory:
                   users:
                      admin: { password: admin, roles: ROLE_ADMIN }
             
     encoders:
          Symfony\Component\Security\Core\User\User: plaintext  