security:
     firewalls:
        admin_secured_area:
            provider: evaluation_admin_chain
            pattern: ^/admin
            anonymous: ~
            form_login: 
                login_path: evaluation_admin_login
                check_path: evaluation_admin_login_check
                always_use_default_target_path: true
                default_target_path: evaluation_admin_console
            logout:
                path: evaluation_admin_logout
                target: evaluation_admin_login
            
     access_control:
                 - { path: ^/$,      roles: IS_AUTHENTICATED_ANONYMOUSLY }
                 - { path: ^/admin$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
                 - { path: ^/admin/, roles: ROLE_ADMIN_USER }
                 
     providers:
          #登录网站后台所使用的超级管理员
          evaluation_super_admin:
            memory:
                users:
                    admin: { password: admin,roles:ROLE_ADMIN_USER}
          #登录网站后台所使用的用户提供者
          evaluation_admin:
               entity:
                   class: EvaluationCommonBundle:AdminUser
                   property: username
          evaluation_admin_chain:
               chain: 
                  providers: [evaluation_super_admin,evaluation_admin]
                  
     encoders: 
         Symfony\Component\Security\Core\User\User: plaintext      
     
          
     
                   
                  
                   