security:
     firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            form_login: ~
               
     access_control: 
                 - { path: ^/admin/, roles: ROLE_ADMIN }

     providers:
       in_memory:
          memory:
           users:
             admin: { password: admin, roles: ROLE_ADMIN }
             
     encoders:
          Symfony\Component\Security\Core\User\User: plaintext  