#民主评价的登陆验证界面
evaluation_web_login_check:
    pattern:  /authentic
    defaults: { _controller: EvaluationWebBundle:Layout:authentic } 

#网站前台的退出登陆
evaluation_web_logout:
    pattern:  /logout
    defaults: { _controller: EvaluationWebBundle:Layout:logout}

#网站前台的控制台页面
evaluation_web_console:
    pattern:  /console
    defaults: { _controller: EvaluationWebBundle:Layout:console }
    
#网站前台的民主评价参与页面
evaluation_evaluate_join:
    pattern:  /evaluate/join
    defaults: { _controller: EvaluationWebBundle:Evaluate:join } 
    
