parameters:
#    evaluation_admin.example.class: Evaluation\AdminBundle\Example

services:
   web_bundle.form.type.evaluate_join:
       class: Evaluation\WebBundle\Form\Type\EvaluateJoinType
       arguments: [@doctrine]
       tags:
           - { name: form.type, alias: evaluate_join_form }
   
