evaluation_admin_console:
    pattern:  /console
    defaults: { _controller: EvaluationAdminBundle:Layout:console}

#民主测评相关   
evaluation_evaluation_read:
    pattern:  /evaluate/read
    defaults: { _controller: EvaluationAdminBundle:Evaluation:read}
    
evaluation_evaluation_create:
    pattern:  /evaluate/create
    defaults: { _controller: EvaluationAdminBundle:Evaluation:create}
  
#民主测评中的测评单位
evaluation_evaluate_school_read:
    pattern:  /evaluate-school/read
    defaults: { _controller: EvaluationAdminBundle:EvaluateSchool:read}
    
evaluation_evaluate_school_create:
    pattern:  /evaluate-school/create
    defaults: { _controller: EvaluationAdminBundle:EvaluateSchool:create}
    
#民主测评中的测评对象 
evaluation_evaluated_person_read:
    pattern:  /evaluated-person/read
    defaults: { _controller: EvaluationAdminBundle:EvaluatedPerson:read}
    
evaluation_evaluated_person_create:
    pattern:  /evaluated-person/create
    defaults: { _controller: EvaluationAdminBundle:EvaluatedPerson:create} 
  
#系统管理员测评相关    
evaluation_admin_user_read:
    pattern:  /admin-user/read
    defaults: { _controller: EvaluationAdminBundle:AdminUser:read}
    
evaluation_admin_user_create:
    pattern:  /admin-user/create
    defaults: { _controller: EvaluationAdminBundle:AdminUser:create}
    
