evaluation_admin_console:
    pattern:  /admin/console
    defaults: { _controller: EvaluationAdminBundle:Layout:console}

#民主测评相关   
evaluation_evaluate_read:
    pattern:  /admin/evaluate/read
    defaults: { _controller: EvaluationAdminBundle:Evaluate:read}
    
evaluation_evaluate_create:
    pattern:  /admin/evaluate/create
    defaults: { _controller: EvaluationAdminBundle:Evaluate:create}
  
#民主测评中的测评单位
evaluation_evaluate_school_read:
    pattern:  /admin/evaluate-school/read
    defaults: { _controller: EvaluationAdminBundle:EvaluateSchool:read}
    
evaluation_evaluate_school_create:
    pattern:  /admin/evaluate-school/create
    defaults: { _controller: EvaluationAdminBundle:EvaluateSchool:create}
    
#民主测评中的测评对象 
evaluation_evaluated_person_read:
    pattern:  /admin/evaluated-person/read
    defaults: { _controller: EvaluationAdminBundle:EvaluatedPerson:read}
    
evaluation_evaluated_person_create:
    pattern:  /admin/evaluated-person/create
    defaults: { _controller: EvaluationAdminBundle:EvaluatedPerson:create} 
  
  
  
#系统管理员测评相关    
evaluation_user_read:
    pattern:  /admin/user/read
    defaults: { _controller: EvaluationAdminBundle:User:read}
    
evaluation_user_create:
    pattern:  /admin/user/create
    defaults: { _controller: EvaluationAdminBundle:User:create}
    
