#网站后台的检测登录的路由
evaluation_admin_login_check:
    pattern:  /authentic
    defaults: { _controller: EvaluationAdminBundle:Layout:authentic }  

#网站后台的退出登陆的页面   
evaluation_admin_logout:
    pattern:  /logout
    defaults: { _controller: EvaluationAdminBundle:Layout:logout}  
  
#网站后台的控制台页面
evaluation_admin_console:
    path:  /console
    defaults: { _controller: EvaluationAdminBundle:Layout:console}
 
#民主测评相关   
evaluation_evaluate_read:
    pattern:  /evaluation/read
    defaults: { _controller: EvaluationAdminBundle:Evaluation:read}

#民主测评的创建相关    
evaluation_evaluate_create:
    pattern:  /evaluation/create
    defaults: { _controller: EvaluationAdminBundle:Evaluation:create}

evaluation_evaluate_check_create:
    pattern:  /evaluation/check-create
    defaults: { _controller: EvaluationAdminBundle:Evaluation:checkCreate}
    
#民主测评的编辑相关    
evaluation_evaluate_update:
    pattern:  /evaluation/update/{id}
    defaults: { _controller: EvaluationAdminBundle:Evaluation:update}
    requirements: 
           id: \d+

evaluation_evaluate_check_update:
    pattern:  /evaluation/check-update/{id}
    defaults: { _controller: EvaluationAdminBundle:Evaluation:checkUpdate}    
    requirements: 
           id: \d+
           
#民主测评的删除相关    
evaluation_evaluate_delete:
    pattern:  /evaluation/delete/{id}
    defaults: { _controller: EvaluationAdminBundle:Evaluation:delete}
    
#民主测评的测评结果导出相关
evaluation_evaluate_result_export:
    pattern:  /evaluation/result-export/{id}
    defaults: { _controller: EvaluationAdminBundle:Evaluation:resultExport}
    
#民主测评的测评结果导出相关
evaluation_evaluate_user_export:
    pattern:  /evaluation/user-export/{id}
    defaults: { _controller: EvaluationAdminBundle:Evaluation:userExport}
    
#民主测评的汇总数据结果导出，选择哪几项数据，导出哪几个评价
evaluation_data_summary_result_export:
    pattern:  /evaluation/data/summary-result-export
    defaults: { _controller: EvaluationAdminBundle:Data:summaryResultExport}  
    
    

#民主测评的编辑相关       
evaluation_evaluate_update:
    pattern:  /evaluation/update/{id}
    defaults: { _controller: EvaluationAdminBundle:Evaluation:update}    
    
#民主测评中的测评单位
evaluation_evaluate_school_read:
    pattern:  /evaluate-school/read
    defaults: { _controller: EvaluationAdminBundle:EvaluateSchool:read}
    
evaluation_evaluate_school_create:
    pattern:  /evaluate-school/create
    defaults: { _controller: EvaluationAdminBundle:EvaluateSchool:create}
    
evaluation_evaluate_school_check_create:
    pattern:  /evaluate-school/check-create
    defaults: { _controller: EvaluationAdminBundle:EvaluateSchool:checkCreate}    
    
    
#民主测评中的测评单位删除相关
evaluation_evaluate_school_delete:
    pattern:  /evaluate-school/delete/{id}
    defaults: { _controller: EvaluationAdminBundle:EvaluateSchool:delete}

#民主测评中的测评单位编辑相关    
evaluation_evaluate_school_update:
    pattern:  /evaluate-school/update/{id}
    defaults: { _controller: EvaluationAdminBundle:EvaluateSchool:update}
    
#民主测评中的测评对象 
evaluation_evaluated_person_read:
    pattern:  /evaluated-person/read
    defaults: { _controller: EvaluationAdminBundle:EvaluatedPerson:read}
   
#民主测评中的测评对象的创建相关 
evaluation_evaluated_person_create:
    pattern:  /evaluated-person/create
    defaults: { _controller: EvaluationAdminBundle:EvaluatedPerson:create}
evaluation_evaluated_person_check_create:
    pattern:  /evaluated-person/check-create
    defaults: { _controller: EvaluationAdminBundle:EvaluatedPerson:checkCreate}   
    
    
evaluation_evaluated_person_update:
    pattern:  /evaluated-person/update
    defaults: { _controller: EvaluationAdminBundle:EvaluatedPerson:update} 
    
evaluation_evaluated_person_delete:
    pattern:  /evaluated-person/delete/{id}
    defaults: { _controller: EvaluationAdminBundle:EvaluatedPerson:delete} 
  
#系统管理员列表    
evaluation_admin_user_read:
    path:  /admin-user/read
    defaults: { _controller: EvaluationAdminBundle:AdminUser:read}

#系统管理员创建相关    
evaluation_admin_user_create:
    path:  /admin-user/create
    defaults: { _controller: EvaluationAdminBundle:AdminUser:create}
    
evaluation_admin_user_check_create:
    path:  /admin-user/check-create
    defaults: { _controller: EvaluationAdminBundle:AdminUser:checkCreate}
    
evaluation_admin_user_update:
    pattern:  /admin-user/update
    defaults: { _controller: EvaluationAdminBundle:AdminUser:update}
    
#系统管理员删除相关    
evaluation_admin_user_delete:
    path:  /admin-user/delete/{id}
    defaults: { _controller: EvaluationAdminBundle:AdminUser:delete}
