evaluation_admin_console:
    pattern:  /console
    defaults: { _controller: EvaluationAdminBundle:Layout:console}

#民主测评相关   
evaluation_evaluate_read:
    pattern:  /evaluation/read
    defaults: { _controller: EvaluationAdminBundle:Evaluation:read}
    
evaluation_evaluate_create:
    pattern:  /evaluation/create
    defaults: { _controller: EvaluationAdminBundle:Evaluation:create}
    
evaluation_evaluate_delete:
    pattern:  /evaluation/delete
    defaults: { _controller: EvaluationAdminBundle:Evaluation:delete}
    
evaluation_evaluate_update:
    pattern:  /evaluation/update
    defaults: { _controller: EvaluationAdminBundle:Evaluation:update}    
    
#民主测评中的测评单位
evaluation_evaluate_school_read:
    pattern:  /evaluate-school/read
    defaults: { _controller: EvaluationAdminBundle:EvaluateSchool:read}
    
evaluation_evaluate_school_create:
    pattern:  /evaluate-school/create
    defaults: { _controller: EvaluationAdminBundle:EvaluateSchool:create}
    
evaluation_evaluate_school_delete:
    pattern:  /evaluate-school/create
    defaults: { _controller: EvaluationAdminBundle:EvaluateSchool:delete}
    
evaluation_evaluate_school_update:
    pattern:  /evaluate-school/create
    defaults: { _controller: EvaluationAdminBundle:EvaluateSchool:update}
    
#民主测评中的测评对象 
evaluation_evaluated_person_read:
    pattern:  /evaluated-person/read
    defaults: { _controller: EvaluationAdminBundle:EvaluatedPerson:read}
    
evaluation_evaluated_person_create:
    pattern:  /evaluated-person/create
    defaults: { _controller: EvaluationAdminBundle:EvaluatedPerson:create}
    
evaluation_evaluated_person_update:
    pattern:  /evaluated-person/update
    defaults: { _controller: EvaluationAdminBundle:EvaluatedPerson:update} 
    
evaluation_evaluated_person_delete:
    pattern:  /evaluated-person/delete
    defaults: { _controller: EvaluationAdminBundle:EvaluatedPerson:delete} 
  
#系统管理员测评相关    
evaluation_admin_user_read:
    pattern:  /admin-user/read
    defaults: { _controller: EvaluationAdminBundle:AdminUser:read}
    
evaluation_admin_user_create:
    pattern:  /admin-user/create
    defaults: { _controller: EvaluationAdminBundle:AdminUser:create}
    
evaluation_admin_user_update:
    pattern:  /admin-user/create
    defaults: { _controller: EvaluationAdminBundle:AdminUser:update}
    
evaluation_admin_user_delete:
    pattern:  /admin-user/create
    defaults: { _controller: EvaluationAdminBundle:AdminUser:delete}
