parameters:
#    evaluation_admin.example.class: Evaluation\AdminBundle\Example

services:
#    evaluation_admin.example:
#        class: %evaluation_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
