parameters:
#    evaluation_admin.example.class: Evaluation\AdminBundle\Example

services:
   common_bundle.form.type.evaluated_person:
       class: Evaluation\AdminBundle\Form\Type\EvaluatedPersonType
       arguments: [@doctrine]
       tags:
           - { name: form.type, alias: evaluated_person_form }
