parameters:
#    evaluation_admin.example.class: Evaluation\AdminBundle\Example

services:
   admin_bundle.form.type.evaluated_person:
       class: Evaluation\AdminBundle\Form\Type\EvaluatedPersonType
       arguments: [@doctrine]
       tags:
           - { name: form.type, alias: evaluated_person_form }
           
   admin_bundle.form.type.admin_user:
       class: Evaluation\AdminBundle\Form\Type\AdminUserType
       tags:
           - { name: form.type, alias: admin_user_form }
           
   admin_bundle.form.type.evaluate_school:
       class: Evaluation\AdminBundle\Form\Type\EvaluateSchoolType
       tags:
           - { name: form.type, alias: evaluate_school_form }
           
   admin_bundle.form.type.evaluation:
       class: Evaluation\AdminBundle\Form\Type\EvaluationType
       arguments: [@doctrine]
       tags:
           - { name: form.type, alias: evaluation_form }