Evaluation\CommonBundle\Entity\EvaluatedPerson:
  constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
              fields: [schoolId,realname]
              errorPath: realname
              message: '该测评单位中已经存在该用户姓名'
  properties:
       realname:
           - NotBlank: { message:'真实姓名不能为空'}
  
#系统管理员的相关实体的约束         
Evaluation\CommonBundle\Entity\AdminUser:
  constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
              fields: [realname]
              message: '该用户的真实姓名已经存在'
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
              fields: [username]
              message: '该用户的登录账号已经存在'
  properties:
       realname:
           - NotBlank: { message:'真实姓名不能为空'}
           