#默认的路由，如果在网站地址什么都不输入，就直接跳到用户的登陆页
evaluation_common_homepage:
    pattern:  /
    defaults: { _controller: EvaluationWebBundle:User:login }
    
evaluation_admin_login:
    pattern:  /admin
    defaults: { _controller: EvaluationAdminBundle:Layout:login }